module.exports = function mapMovieModel(movieFromDb) {
    const { 
         tmdbId,
         title,
         originalTitle,
         language,
         releaseYear,
         releaseDate,
         genres,
         plot,
         runtime,
         budget,
         revenue,
         homepage,
         status,
         posterUrl,
         backdropUrl,
         trailerUrl,
         trailerYouTubeId,
         imdbRating,
         searchL,
         keywords,
         countriesOfOrigin,
         languages,
         cast,
         director,
         production,
         awardsSummary,
    } = movieFromDb;

    return {
        id: tmdbId,
        title,
        originalTitle,
        language,
        releaseYear,
        releaseDate,
        genres,
        plot,
        runtime,
        budget,
        revenue,
        homepage,
        status,
        posterUrl,
        backdropUrl,
        trailerUrl,
        trailerYouTubeId,
        imdbRating,
        searchL,
        keywords,
        countriesOfOrigin,
        languages,
        cast,
        director,
        production,
        awardsSummary,
    }
};